// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcRepositoryPatternDemo.DAL;

#nullable disable

namespace MvcRepositoryPatternDemo.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20231005111506_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MvcRepositoryPatternDemo.Models.Book", b =>
                {
                    b.Property<long>("bookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Bigint")
                        .HasColumnName("book_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("bookId"));

                    b.Property<string>("Auther")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("auther");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasColumnName("title");

                    b.HasKey("bookId");

                    b.ToTable("book", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
